name: ExifPurge
options:
  bundleIdPrefix: com.portfolio.vibe
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

targets:
  ExifPurge:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ExifPurge
    resources:
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.portfolio.vibe.ExifPurge
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentBlue
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "ExifPurge needs access to save cleaned photos to your library."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "ExifPurge needs access to read photo metadata for removal."
